-- hospital_seed.sql
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('내과');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('외과');
INSERT INTO DEPARTMENT (DEPT_NAME) VALUES ('소아과');
INSERT INTO DOCTOR (NAME, DEPT_ID, PHONE, EMAIL) VALUES ('김의사', 1, '010-1000-1000', 'kimdoc@hospital.com');
